AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda layer for Image Analyzer app
Resources:
  imageAnalyzerLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: image-analyzer-lambda-layer
      Description: null
      ContentUri: s3://toms-lambda-eu-west-1/sam/layers/8184e48a54a136a904591e80911226c0
      CompatibleRuntimes:
      - java11
      RetentionPolicy: Retain
