AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for notification
Resources:
  imageAnalyzerLambdaNotifier:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: image-analyzer-lambda-notifier
      AutoPublishAlias: prod
      Handler: cloud.developing.imageanalyzer.notifier.Notifier::send
      Runtime: java11
      CodeUri: s3://toms-lambda-eu-west-1/sam/lambdas/087ad42c07ec63cd9da26f38da3f68c9
      MemorySize: 512
      Timeout: 30
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/lambda_exec_role
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:image-analyzer-lambda-layer:1
      Environment:
        Variables:
          TOPIC_ARN:
            Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:image-analyzer-topic
          RECIPIENTS: notify@developing.cloud
          FROM: ia@developing.cloud
